// Generated by CoffeeScript 1.4.0
(function() {

  define(['comb/section'], function(Section) {
    'use strict';

    var Template;
    return Template = (function() {

      function Template(spec, node, partials, verbose) {
        this.spec = spec;
        this.node = node;
        this.partials = partials != null ? partials : {};
        if (verbose == null) {
          verbose = false;
        }
        this.spec.verbose = verbose;
        this.root = new Section(0, this.spec, this.partials, this.node, 0, 0);
      }

      Template.prototype.getRoot = function() {
        return this.root.getRoot();
      };

      Template.prototype.getValues = function() {
        return this.root.getValues([])[0];
      };

      return Template;

    })();
  });

}).call(this);
